src/alr-origins-source_archive.adb
src/alr-origins-source_archive.ads

This change adds files that were lost in some git rebase for PR #55. Sorry again about the mess!

Add missing sources files (Alr.Origins.Source_Archive)

---

.gitmodules
alr.gpr
alr_env.gpr
doc/catalog-format-spec.rst
src/alire/alire-index.adb
src/alire/alire-index.ads
src/alire/alire-licensing.adb
src/alire/alire-licensing.ads
src/alire/alire-toml_expressions.adb
src/alire/alire-toml_expressions.ads
src/alire/alire-toml_index.adb
src/alire/alire-toml_index.ads
src/alire/alire-utils.ads
src/alire/alire.ads
src/alr/alr-bootstrap.ads
src/alr/alr-commands-dev.adb
src/alr/alr-commands-show.adb
src/alr/alr-commands-update.adb
src/alr/alr-commands.adb

These commits implement the use of a TOML index rather than in-code index. See https://github.com/alire-project/alire/pull/41 for the context.
(edit: updated to mention TOML rather than JSON, now that the PR is updated)

Switch to a TOML-based index

---

src/alire/alire-defaults.ads
src/alire/alire-environment.ads
src/alire/alire-properties-labeled.ads
src/alire/alire-properties.ads
src/alire/alire-releases.adb
src/alire/alire-releases.ads
src/alire/alire-toml_keys.ads
src/alire/alire-utils.adb
src/alire/alire-utils.ads
src/alr/alr-commands-init.adb
src/alr/alr-commands.adb
src/alr/alr-commands.ads

Uses definite instead of conditional properties/dependencies, so its a downgrade from original functionality. Still, it contains some valid changes so it has to be merged

Discarded attempt for TOML export

---

src/alire/alire-actions.ads
src/alire/alire-conditional_trees.adb
src/alire/alire-conditional_trees.ads
src/alire/alire-dependencies.adb
src/alire/alire-dependencies.ads
src/alire/alire-interfaces.ads
src/alire/alire-origins.adb
src/alire/alire-origins.ads
src/alire/alire-properties-labeled.ads
src/alire/alire-properties-licenses.ads
src/alire/alire-properties-platform.ads
src/alire/alire-properties-scenarios.ads
src/alire/alire-properties.adb
src/alire/alire-properties.ads
src/alire/alire-releases-toml_io.adb
src/alire/alire-releases.adb
src/alire/alire-toml_index.adb
src/alire/alire-toml_keys.ads
src/alire/alire.ads

Export releases to TOML #2

---

scripts/shiptest.sh
src/alire/alire-conditional_trees.adb
src/alire/alire-properties-licenses.ads
src/alire/alire-properties-platform.ads
src/alire/alire-properties-scenarios.adb
src/alire/alire-properties-scenarios.ads
src/alire/alire-properties.ads
src/alire/alire-toml_adapters.ads
src/alire/alire-toml_keys.ads

- Use license proper name during toml export
- Export scenario variables/externals

Fix assorted TODOs related to #73

---

src/alire/alire-os_lib-subprocess.adb
src/alire/alire-os_lib-subprocess.ads
src/alire/alire-os_lib.ads
src/alire/alire-toml_index.ads
src/alire/alire-utils.adb
src/alire/alire-utils.ads
src/alire/alire.adb
src/alire/alire.ads
src/alr/alr-os_lib.adb
src/alr/alr-os_lib.ads
src/alr/alr-utils.adb
src/alr/alr-utils.ads
src/alr/alr.ads

Support things moved from Alr.* into Alire.* Also a new Alire.Outcome type to reduce use of exceptions, same as Alire.TOML_Index.Load_Result.

Refactorings to help with WIP for #69

---

src/alire/alire-directories.adb
src/alire/alire-directories.ads
src/alire/alire-vcss-git.adb
src/alire/alire-vcss-git.ads
src/alire/alire-vcss.adb
src/alire/alire-vcss.ads
src/alire/alire.ads
src/alr/alr-commands.adb
src/alr/alr-files.adb
src/alr/alr-files.ads
src/alr/alr-paths.ads

- Relocation of a few functions in alr.* into alire.*
- Calls to git exposed through Alire.VCSs.Git instead of hidden in calls to Alr.Spawn

More refactorings in support of index command WIP

---

scripts/shiptest.sh

Output more metadata about the CI testing environment

Dump environment info during CI

---

src/alire/alire-index_on_disk.adb
src/alire/alire-toml_index.adb
src/alire/alire.ads
src/alr/alr-commands-clean.adb
src/alr/alr-commands-init.adb
src/alr/alr-commands.adb
testsuite/tests/workflows/init-options/test.py
testsuite/tests/workflows/init-options/test.yaml

Fixes for issues #146 and #148

Minor bugfixes & Alire.Outcome encapsulation

---

shippable.yml

We were using PMdR fork, which has already been merged into AdaCore's

Revert to stock e3-testsuite

---

src/alire/alire-origins.adb

Minor issues that I found while runnin `alr test` on all crates.

Minor fixes related to origins

---

src/alr/alr-commands-get.adb

`alr get` tries to retrieve a specific version (by default, the newest one). Hence, the availability was tested for dependencies during resolution but not for the crate itself, which was found by other code path without taking into account its availability. This PR adds this check.

Fail to `alr get` an unavailable release

---

shippable.yml
src/alr/alr-commands-search.adb
testsuite/tests/get/native-unsupported/test.py

Found those while adding CentOS to CI as unknown test platform.

Fix another unknown-platform-related exception

---

src/alire/alire-directories.adb
src/alire/alire-directories.ads
src/alire/alire-errors.adb
src/alire/alire-errors.ads
src/alire/alire-hashes.ads
src/alire/alire-origins-deployers-git.adb
src/alire/alire-os_lib-subprocess.adb
src/alire/alire-os_lib-subprocess.ads
src/alire/alire-outcomes-indefinite.adb
src/alire/alire-outcomes-indefinite.ads
src/alire/alire.adb
src/alire/alire.ads

General bugs/small changes that were found/needed during folder hashing upcoming PR.

Assorted minor changes

---

alire_common.gpr
alr_env.gpr
src/alire/alire-directories.adb
src/alire/alire-directories.ads
src/alire/alire-vfs.adb
src/alire/alire-vfs.ads

See commit descriptions for more details.

Various minor fixes/feats

---

.github/workflows/ci-linux.yml
README.md

For some reason I can't get right path-based badges.

Fix CI badge

---

src/alr/alr-commands.adb

Global switches take quite some space in the help output and most of the time I presume they're not what the user is looking for.
Instead, global switches are shown when `alr --help` alone is used. A message in each individual command help redirects users to the above, so the hint that global switches exist is still present in
every command help.

Don't pollute a command help with global switches.

---

src/alire/alire-index_on_disk.adb
src/alire/alire-releases.adb
src/alire/alire-releases.ads
testsuite/tests/index/bad-name/test.py
testsuite/tests/index/bad-name/test.yaml
testsuite/tests/show/inside-vs-outside/test.py
testsuite/tests/show/inside-vs-outside/test.yaml

* Use of New_Invalid_Index was inconsistent in Alire.Index_On_Disk, which lead to an exception for invalid index names.
* Fix for the regression in #243 (`alr show` exception in working copy).

Couple of minor bugfixes

---

.github/workflows/ci-linux.yml

This reverts commit 9d1cad2a9775fd5f53b339144a717b1dd8c213f3.

Revert "Temporary change testsing index"

---

src/alire/alire-index_on_disk.adb
src/alire/alire-index_on_disk.ads

Better error on missing git+ when adding an index

---

doc/catalog-format-spec.rst

Fix documentation about `executables` index field.

---

.github/workflows/ci-linux.yml
.github/workflows/ci-macos.yml
.github/workflows/ci-windows.yml
README.md

Also add some more text patterns that should not trigger CI checks

Add the MacOS badge to README
