- .gitignore
- alire.gpr
- src/alire/alire-environment.ads
- src/alire/alire-features-index.adb
- src/alire/alire-features-index.ads
- src/alire/alire-os_lib.adb
- src/alire/alire-os_lib.ads
- src/alire/alire.ads
- src/alr/alr-commands.adb
- src/alr/alr-os_lib.adb
- src/alr/alr-os_lib.ads
- src/alr/alr-paths.ads
And related changes to avoid existing inverse dependencies alire -> alr
Also removed the dependency on global status in Alire.Features.Index.
The idea is to progressively remove other globals that muddle the current code base.
Closes #70
> Separate alire.gpr from alr.gpr

- alire.gpr
- alire_common.gpr
- alr.gpr
As a side effect, there is a single scenario variable left to select the
build profile: ALIRE_BUILD_MODE. This is more convenient, as someone
who wants to build alire using some build mode most probably also wants
to build alr in the same build mode.
> Factor common logic out of alr.gpr and alire.gpr

- src/alire/alire-releases.adb
- src/alire/alire-root.adb
- src/alire/alire-root.ads
- src/alire/alire-toml_index.adb
- src/alire/alire-toml_index.ads
- src/alr/alr-commands.adb
- src/alr/alr-root.adb
- src/alr/alr-root.ads
Commands that apply to a downloaded project rely on getting the release info from a TOML file (since this can be an unreleased project, or a release that has been modified).
I have moved things a bit around in TOML_Index to be able to load a release without indexing it. Since this is your turf, maybe I have missed something in the process.
The main change is adding an extra step after decoding a Pkg, so the releases are not directly indexed.
> Load a single release from a non-index TOML file

- src/alire/alire-dependencies.adb
- src/alire/alire-dependencies.ads
- src/alire/alire-index.adb
- src/alire/alire-origins.adb
- src/alire/alire-root.adb
- src/alire/alire-roots-check_valid.adb
- src/alire/alire-roots-check_valid.ads
- src/alire/alire-roots.ads
- src/alire/alire-toml_index.adb
- src/alire/alire-toml_index.ads
- src/alr/alr-bootstrap.adb
- src/alr/alr-commands-compile.adb
- src/alr/alr-commands-pin.adb
- src/alr/alr-commands-show.adb
- src/alr/alr-commands-test.adb
- src/alr/alr-commands-withing.adb
- src/alr/alr-commands.adb
- src/alr/alr-query.adb
- stress/selftest.sh
Roughly each commit adresses one command, except when new functionality is added.
With this, the old test suite in stress/selftest.sh passes again.
There are still points to address affected by the migration to toml for which I will create new stand-alone issues.
> Fixes #73 in various commands

- src/alire/alire-roots-check_valid.ads
- src/alr/alr-bootstrap.adb
- src/alr/alr-bootstrap.ads
- src/alr/alr-commands-show.adb
Sessions in which the local toml file isn't parsable prevent session commands to succeed. This patch makes this situation explicit, to distinguish a broken session (can't load toml file) from being outside of any session (there is no toml file to load).
> Better detection of broken sessions

- .gitmodules
- src/alire/alire-config.adb
- src/alire/alire-config.ads
- src/alire/alire-defaults.ads
- src/alire/alire-features-index.adb
- src/alire/alire-features-index.ads
- src/alire/alire-index_on_disk-directory.adb
- src/alire/alire-index_on_disk-directory.ads
- src/alire/alire-index_on_disk-git.adb
- src/alire/alire-index_on_disk-git.ads
- src/alire/alire-index_on_disk.adb
- src/alire/alire-index_on_disk.ads
- src/alire/alire-toml_keys.ads
- src/alire/alire.ads
- src/alr/alr-commands-index.adb
- src/alr/alr-commands-index.ads
- src/alr/alr-commands.adb
- src/alr/alr-commands.ads
- src/alr/alr-os_lib.adb
- src/alr/alr-os_lib.ads
Implements #69 
Implementation notes:
Three packages are mainly affected here:
- `Alire.Index_On_Disk`: encapsulates internal implementation of single index actions
- `Alire.Features.Index`: provides the public Alire API for clients
- `Alr.Commands.Index`: implements command-line parsing and uses Alire.Features.Index
Index are loaded in their listing order; if a crate milestone is duplicated, only first one is kept (which is the whole point of priorities; we could err on duplicates, but I fear this can be too restrictive if several public indexes were to exist. This is similar to how `apt` works).
With this set of patches, alr sources and subrepos are no longer checked out for operations requiring an index (instead the default public index is configured when first needed -- we could check …
> Add command for management of indexes

- src/alr/alr-testing-junit.adb
- src/alr/alr-testing-junit.ads
This corrects the issue that, when interrupting `alr test` (or in case of internal error), no junit log was produced at all.
> Flush junit log after each test

- src/alire/alire-releases.ads
Remove the patch/build parts of a version from the crate deployment folder.
Crate folder is still unique due to the commit part
> Fix possibility of forbidden chars in folder name

- src/alire/alire-directories.adb
- src/alire/alire-paths.ads
- src/alr/alr-commands-clean.adb
- src/alr/alr-commands-run.adb
- src/alr/alr-spawn.adb
- src/alr/alr-spawn.ads
- testsuite/tests/workflows/get-build-run-clean/test.py
Instead of building in place, the $root_crate/alire/build folder is used.
Implements #95
> Out-of-tree building

- shippable.yml
Stretch couldn't compile alr, but now Buster is able. We can stick to Debian stable from now on as the Debian "supported" release.
> Use Debian stable instead of testing for CI

- shippable.yml
yaml.safe_load causes an exception. This is a temporal workaround
until the Python expert is back.
> Use previous working e3-testsuite commit

- .gitmodules
- alire.gpr
- alr_env.gpr
- scripts/shiptest.sh
- src/alire/alire-directories.adb
- src/alire/alire-directories.ads
- src/alire/alire-features-index.adb
- src/alire/alire-features-index.ads
- src/alire/alire-index_on_disk.adb
- src/alire/alire-origins-deployers-filesystem.adb
- src/alire/alire-origins-deployers-source_archive.adb
- src/alire/alire-origins-deployers.ads
- src/alire/alire-toml_index.adb
- src/alire/alire.ads
- src/alr/alr-checkout.adb
- src/alr/alr-commands-index.adb
- src/alr/alr-commands-init.adb
- src/alr/alr-commands-test.adb
- src/alr/alr-commands.adb
- src/alr/alr-os_lib.ads
- src/alr/alr-templates.adb
- testsuite/drivers/alr.py
- testsuite/tests/index/local-index-not-found/test.py
- testsuite/tests/index/local-index-not-found/test.yaml
Experimenting with gnacoll-slim to see if we can have our cake and eat it (i.e., no other dependencies).
> Use GNATCOLL.VFS for platform-independent path processing (was #143)

- src/alr/alr-commands.adb
This makes the list more easy to find for users as the other way to get
the list is to run alr without argument, which is not necessarily
intuitive.
> Alr.Commands: Print command list when no help topic is specified

- src/alire/alire-actions.ads
- src/alire/alire-conditional_trees.adb
- src/alire/alire-conditional_trees.ads
- src/alire/alire-dependencies.ads
- src/alire/alire-interfaces.ads
- src/alire/alire-properties-labeled.ads
- src/alire/alire-properties-licenses.ads
- src/alire/alire-properties-platform.ads
- src/alire/alire-properties-scenarios.ads
- src/alire/alire-properties.adb
- src/alire/alire-properties.ads
- src/alire/alire-releases.adb
- src/alire/alire-releases.ads
- src/alire/alire-utils.adb
- src/alire/alire-utils.ads
- src/alr/alr-commands-show.adb
- src/alr/alr-commands-show.ads
- testsuite/fixtures/basic_index/he/hello.toml
- testsuite/tests/show/jekyll/test.py
- testsuite/tests/show/jekyll/test.yaml
Jekyll is a static site generator based on YAML and markdown.  This
output can be used to generate crate pages for a simple Alire website.
The main change of this patch is to introduce a "Yamlable" interface to
describe objects that can produce a text YAML representation, and then
implement this interface for the required types.
> [RFC] Add a Jekyll format option to the show command

- src/alire/alire-releases.adb
- src/alire/alire-releases.ads
- src/alr/alr-commands-show.adb
- src/alr/alr-commands-show.ads
Private properties do not exist in the new TOML index format. Fixes #91
> Remove obsolete private properties from Releases

- src/alire/alire.adb
- src/alire/alire.ads
- src/alire/alire_early_elaboration.adb
- src/alire/alire_early_elaboration.ads
- src/alr/alr-commands.adb
- src/alr/alr-commands.ads
- testsuite/drivers/alr.py
- testsuite/tests/debug/enabled-dump-exception/test.py
- testsuite/tests/debug/enabled-dump-exception/test.yaml
This patch slightly reworks the verbosity system in `alr` to enable both quiet testing without losing important diagnostic messages. To do so, there are now two separate logging "channels"
1. The previous, normal logging facilities, with 4 verbosity levels that go to stdout:
- `-q` (quiet, only error messages)
- `(none)` (only error and warning messages)
- `-v` (verbose)
- `-vv` (extra verbose) (what was `-d` previously)
2. A new debug mode (`-d/--debug`) which will print debug information bypassing any verbosity levels, to stderr.
> Use -d/--debug for specific debug logging

- src/alire/alire_early_elaboration.adb
- src/alr/alr-commands-dev.adb
- src/alr/alr-commands-dev.ads
- src/alr/alr-commands.adb
- src/alr/alr-os_lib.adb
- src/alr/alr.ads
- testsuite/tests/debug/logging-scopes/test.py
- testsuite/tests/debug/logging-scopes/test.yaml
This patch allows passing optional filters to `-d/--debug`, which are substrings that will be matched against the enclosing entity and source file of regular verbosity logging messages.
By passing e.g. `-d+main`, `-d-alr`, etc, the logging output can be filtered out in both blacklist/whitelist mode. Several filters can be given: `-d+main+commands`. 
Using the contrary sign acts as an exception to the filtering: `-d+alr-commands` will whitelist all `alr` messages, but will filter out `commands` messages.
The first sign in the argument puts the filtering in whitelist (+) or blacklist (-) mode. As special cases, giving no substrings illustrate these modes: `-d-` will use an empty blacklist, thus allowing all logging messages to pass through. Contrarily, `-d+` will use an empty whitelist, …
> Enhance -d/--debug with optional debugging scopes

- src/alr/alr-commands-dev.adb
- src/alr/alr-commands.adb
- src/alr/alr-main.adb
- src/alr/gnat-command_line-extra.adb
- src/alr/gnat-command_line-extra.ads
- testsuite/tests/switch-redefinition/test.py
- testsuite/tests/switch-redefinition/test.yaml
Ensure that a command does not redefine a previously defined global switch. More generally, check that the same switch is not defined twice, in either short or long form.
Fixes #111
> Detect duplicate definition of switches

- doc/catalog-format-spec.rst
- scripts/shiptest.sh
- src/alire/alire-hashes-common.adb
- src/alire/alire-hashes-common.ads
- src/alire/alire-hashes-sha512_impl.ads
- src/alire/alire-hashes.ads
- src/alire/alire-index.ads
- src/alire/alire-origins-deployers-source_archive.adb
- src/alire/alire-origins.adb
- src/alire/alire-origins.ads
- src/alire/alire-releases.ads
- src/alire/alire-toml_index.adb
- src/alire/alire-toml_keys.ads
- testsuite/tests/index/origin-no-archive-name/my_index/index/he/hello_world.toml
- testsuite/tests/index/origin-no-archive-name/test.py
Fixes #66 (note that there is wider-scoped discussion there).
We add a hash field (`archive-hash`) to releases that are provided by source files not under version control, hence lacking any form of integrity verification. This hash is recomputed and verified after download. This can be tested e.g. with `alr get --only gnatcoll`.
There is a matching update for this PR in the alire-index repository that provides this hash for existing source file crates.
> Add hash to source archives for integrity verification.

- ISSUES.txt
- pending_libs.txt
- src/alire/alire-releases.adb
- src/alire/alire.ads
- src/alr/alr-templates.adb
Foreseeing that at some point we may want nicer output, perhaps with colorization, I have explicitly commented what is the intended use of logging levels. This has not always been adhered to strictly, but by putting it in writing it should be easier to be consistent moving forward.
This should appear at some point wherever we put the information for wannabe contributors.
> Document use of log levels and corresponding output tweaks.

- elim/ajunitgen.gpr
- elim/alire.gpr
- elim/alr.gpr
- elim/run.sh
I expect it will be useful to locate scattered dead code from the removal of the old index.
The PR adds a few mock project files since it seems gnatelim does not yet understand aggregate projects.
> Set up gnatelim for future use

- src/alire/alire-dependencies.adb
- src/alire/alire-toml_index.adb
- src/alire/alire.adb
- src/alire/alire.ads
- testsuite/tests/show/crate-name-casing/test.py
- testsuite/tests/show/crate-name-casing/test.yaml
This was manifesting in some dependencies being reported as unavailable.
We might go even further and force all crate names to be lowercase upon loading. For now, following the Ada example, case is preserved.
> Fix case insensitivity for crate names

- scripts/shiptest.sh
A concrete index commit was forced for CI during the addition of the `archive-hash` field. This PR reverts that temporary measure.
> Re-enable using the master index in CI

- src/alire/alire-origins-deployers.adb
- src/alire/alire-origins-deployers.ads
- src/alire/alire-platform.ads
- src/alire/os_linux/alire-platform.adb
- src/alr/alr-bootstrap.adb
- src/alr/alr-checkout.adb
- src/alr/alr-commands-get.adb
- src/alr/alr-commands-show.adb
- src/alr/alr-os_lib.ads
- src/alr/alr-query.adb
- testsuite/fixtures/basic_index/ma/make.toml
- testsuite/tests/get/native-unsupported/test.py
- testsuite/tests/get/native-unsupported/test.yaml
As part of the effort to better deal with native packages, this is a minimal patch to avoid general exceptions in unsupported distributions, that fixes #181, #180, #177, #169 (in the sense that clearer errors are emitted instead of the general internal failure one).
My plan is to rework the native situation as seamlessly as possible pre/post beta along these lines:
- Do not assume the platform is known (this patch) so people don't get bizarre errors.
- Allow resolution/retrieval of crates that are only missing native packages (the "permissive mode" we talked in #65).
- In that case (missing native dependencies), use current native crates to give the user a hint of what they should provide manually (and to warn that the build will likely fail otherwise).
That would be my minimum target for …
> Fix errors about native packages in unknown platforms.

- src/alire/alire-features-index.adb
- src/alire/alire-features-index.ads
- src/alire/alire-hashes-common.adb
- src/alire/alire-origins.adb
- src/alire/alire-origins.ads
- src/alire/alire-toml_adapters.adb
- src/alr/alr-commands-dev.adb
- src/alr/alr-commands-dev.ads
Salvage the commits in #212 that allow using `alr dev --hash`, which at this time works only for source archives.
> Developer feature to compute hashes of origins

- src/alire/alire-origins-deployers-filesystem.adb
- src/alire/alire-origins-deployers-filesystem.ads
- src/alire/alire-origins-deployers-source_archive.ads
- src/alire/alire-origins-deployers.adb
- src/alire/alire-origins-deployers.ads
- src/alire/alire-origins.ads
This is done to allow a Filesystem origin to report True/False depending on its two use cases: deploying a local tarball (True) or a local folder (False) -- the later is a working copy that is expected to change.
An alternative would be to separate Filesystem into two origin kinds, but that is much more work for no other practical benefit than this check.
> Refactor Supports_Hashing as a member function

- src/alire/alire-features-index.adb
- src/alire/alire-origins-deployers-apt.adb
- src/alire/alire-origins-deployers-apt.ads
- src/alire/alire-origins-deployers-filesystem.adb
- src/alire/alire-origins-deployers-filesystem.ads
- src/alire/alire-origins-deployers-git.adb
- src/alire/alire-origins-deployers-git.ads
- src/alire/alire-origins-deployers-hg.adb
- src/alire/alire-origins-deployers-hg.ads
- src/alire/alire-origins-deployers-source_archive.adb
- src/alire/alire-origins-deployers-source_archive.ads
- src/alire/alire-origins-deployers-svn.adb
- src/alire/alire-origins-deployers-svn.ads
- src/alire/alire-origins-deployers.adb
- src/alire/alire-origins-deployers.ads
This patch adds an extra Fetch step to `Origins.Deployers`. This way, instead of (Fetch & Unpack) -> Verify, we Fetch -> Verify -> Unpack. This is more in line with the workflow for source archives.
> Reorganize retrieval/verification steps for origins

- .github/workflows/ci-linux.yml
- doc/publishing.md
- src/alr/alr-commands-dev.adb
- src/alr/alr-commands-dev.ads
- src/alr/alr-commands-publish.adb
- src/alr/alr-commands-publish.ads
- src/alr/alr-commands-skeleton.ads
- src/alr/alr-commands.adb
- src/alr/alr-commands.ads
- testsuite/tests/publish/hash/test.py
- testsuite/tests/publish/hash/test.yaml
Intended to eventually automate the publication of crates/releases, for now:
- It allows hashing an origin (`dev --hash` has been moved to `publish --hash`)
- Its help redirects users to detailed instructions that we'll put up in [doc/publishing.md]
> Minimal `publish` command

- src/alire/alire-platforms.ads
- src/alr/alr-platform.adb
Hello,
While trying to add the 2019 release of GNATCOLL using my local GCC 9.2.0 toolchain, I could not express properly compiler depedencies. This commit does what’s necessary short term, but I guess we would need a more scalable way to handle GNAT releases in the future. Anyway, I hope this helps in the meantime. :-) Cheers!
> Add handling for recent FSF and Community GNAT releases

- src/alr/alr-commands-help.adb
- src/alr/alr-commands-help.ads
- src/alr/alr-commands.adb
- src/alr/alr-commands.ads
- testsuite/tests/help/equivalent_help/test.py
We have several instances (#242, probably more) where errors are detected but no further information is provided. Besides providing better information on the spot, with this patch we can define more general topics that the user can check for help.
Also the help support becomes a bit better structured, with some parts being moved from Alr.Commands to Alr.Commands.Help.
A minimal new topic is included: `identifiers` describes the rules for crate/index names.
> Extend `alr help` to support non-command topics

- src/alire/alire-origins-deployers-apt.adb
- src/alire/alire.adb
- src/alire/alire.ads
This patch removes inconsistent use of `Internal_Error`/`Unconstrained_Error` in favor of `Checked_Error`.
We were using those in just a couple of places when explicitly checking for errors, and that's what `Checked_Error` is for.
`Internal_Error` is directly replaced by `Checked_Error`. `Unconstrained_Error` is renamed as `Raise_Checked_Error`, which logs to stderr (when enabled) the error message, and raises a `Checked_Error` with the message stored with `Alire.Errors` as the information for the user.
> Deprecate Internal_Error/Unconstrained_Error

- src/alr/alr-bootstrap.adb
- src/alr/alr-bootstrap.ads
- src/alr/alr-platform.adb
Fixes #236
Stop-gag measure until we fully address the cross-compiling situation. I see that cross-compiling-gnats have unpredictable names like `riscv32-elf-gnat`, so perhaps it will be the responsibility of the user to supply the actual gnat name?
> Check for GNAT in path before invoking it

- doc/catalog-format-spec.rst
- src/alire/alire-conditional.ads
- src/alire/alire-containers.adb
- src/alire/alire-dependencies.adb
- src/alire/alire-dependencies.ads
- src/alire/alire-releases.adb
- src/alire/alire-releases.ads
- src/alire/alire-types.ads
- src/alr/alr-commands-get.adb
- src/alr/alr-commands-show.adb
- src/alr/alr-commands-test.adb
- src/alr/alr-commands-withing.adb
- src/alr/alr-parsers.adb
- src/alr/alr-parsers.ads
- src/alr/alr-query.adb
- src/alr/alr-query.ads
- testsuite/tests/get/native-hint/test.py
- testsuite/tests/show/jekyll/test.py
- testsuite/tests/workflows/init-with-pin/test.py
As discussed in #104, current versions sets were limited to one restriction. I've added more general expressions to `Semantic_Versioning` which are readily usable in alire with this patch.
We discussed a possibility of using ',' and arrays for "and"/"or" conditions but after checking similar expressions in `apt` and `opam` I did likewise using '&', '|' respectively, which I found clearer. Example:
`foo = "^3.0 | (^2.0 & /=2.1.3)"`
So current dependencies don't change and more expressive ones can be used when needed.
I intend to take advantage of these more general expressions also to address the unsustainable compiler situation pointed out by @pmderodat in #241 as part of the native package rework. I will discuss this idea in a separate issue.
Fixes #104
> More general version sets for dependencies

- src/alire/alire-origins-deployers-source_archive.adb
- src/alire/alire-os_lib-subprocess.adb
- src/alr/alr-spawn.adb
Unlike for `Checked_Spawn_And_Capture`
`-q` should continue working.
Now things are much more verbose (the user by default sees fetches, clones and builds), but since we no longer have the line-catcher spinner this might serve for the time being.
> Let output of Checked_Spawn go to console

- src/alire/alire-releases.adb
When the project file path contains several directories, we are using Head() to keep the directory part.
The Head() function cannot be used because it seeks forward and stops at the first '/' and hence keeps only the first directory component.
Instead we should seek backward to find the last '/' in the path and return the path from the beginning up to the last part (a Head() function that seeks backward and not forward).
> The project path can contain several directories and we must take each of them

- src/alire/alire-origins-deployers-source_archive.adb
We had this with `wget` so long downloads don't make `alr` appear to do nothing. It can still be silenced with `-q`.
> Restore progress bar with `curl` in default log level

- src/alire/alire-requisites-booleans.adb
Otherwise we got a generic assertion failure.
> Better diagnostic when a TOML Boolean was expected

- scripts/ci-github.sh
Some distros are already moving to Python 3 (e.g. CentOS) and this is likely to continue as support for Python 2 ends. Until the e3 testsuite is migrated we ensure we are using/finding the Python 2 interpreter.
> Explicitly use python2 for test suite
